ARDUINO_DIR=/home/weictr/opt/arduino/arduino-1.8.13/
ARDMK_DIR=Arduino-Makefile
AVR_TOOLS_DIR=/usr

BOARD_TAG=uno
MONITOR_PORT=/dev/ttyUSB0

#ARDUINO_LIBS=SoftwareSerial

AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf

include $(ARDMK_DIR)/Arduino.mk
